#############################
###    shared settings    ###
#############################
x-common-settings: &common
  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s
  devices:
    - /dev:/dev
  environment:
    - DISPLAY=${DISPLAY}

  
############################
###   shared settings    ###
############################
x-workspace-settings: &ws
  build: 
    context: .  
    dockerfile: Dockerfile
    target: user
  image: hrcnthu/viperx-300s:default
  volumes:
    # GUI
    - $HOME/.Xauthority:/.Xauthority:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    # ROS2 container communication
    - /dev/shm:/dev/shm:rw
    # Udev rules 
    - /dev:/dev:rw
    - /run/udev:/run/udev
    - /etc/udev:/etc/udev

    # Workspace
    - ./xsarm_amd64_install.sh:/xsarm_amd64_install.sh


##############################
###   Container Services   ###
##############################
services:
  dev:
    <<: [*common, *ws]
    container_name: dev
    command: ["/bin/bash"]
