name: VIPERX 300S image (x86)

on:
  push:
    branches: [ main, pomelo925 ]
    paths:
      - ros2/docker/Dockerfile
      - ros2/docker/compose.yml
      - .github/workflows/docker.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Repo Checkout 
      uses: actions/checkout@v4
    - 
      name: Docker meta
      id: meta
      # Ref: https://github.com/docker/metadata-action
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/viperx-300s
        tags: default
    - 
      name: Docker Hub Log-in
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    # Build Docker image
    - 
      name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: ros2/docker
        load: true # Load the image into Docker environment
        tags: ${{ steps.meta.outputs.tags }}
        push: false
        no-cache: true

    # Push Docker image to registry
    - 
      name: Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ros2/docker/
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        no-cache: true